package me.sonico.bean;

import java.util.Date;

//@Table(name="t_article")
//@Table
public class TArticle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.article_id
     *
     * @mbggenerated
     */
//    @Id

    private Long articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.article_type_id
     *
     * @mbggenerated
     */
    private Long articleTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.article_summary
     *
     * @mbggenerated
     */
    private String articleSummary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.article_title
     *
     * @mbggenerated
     */
    private String articleTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.article_file_url
     *
     * @mbggenerated
     */
    private String articleFileUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.public_datetime
     *
     * @mbggenerated
     */
    private Date publicDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.update_datetime
     *
     * @mbggenerated
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.article_status
     *
     * @mbggenerated
     */
    private Boolean articleStatus;

    public String getArticleAuthor() {
        return articleAuthor;
    }

    public void setArticleAuthor(String articleAuthor) {
        this.articleAuthor = articleAuthor;
    }

    private String articleAuthor;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.article_id
     *
     * @return the value of t_article.article_id
     *
     * @mbggenerated
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.article_id
     *
     * @param articleId the value for t_article.article_id
     *
     * @mbggenerated
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.article_type_id
     *
     * @return the value of t_article.article_type_id
     *
     * @mbggenerated
     */
    public Long getArticleTypeId() {
        return articleTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.article_type_id
     *
     * @param articleTypeId the value for t_article.article_type_id
     *
     * @mbggenerated
     */
    public void setArticleTypeId(Long articleTypeId) {
        this.articleTypeId = articleTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.article_summary
     *
     * @return the value of t_article.article_summary
     *
     * @mbggenerated
     */
    public String getArticleSummary() {
        return articleSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.article_summary
     *
     * @param articleSummary the value for t_article.article_summary
     *
     * @mbggenerated
     */
    public void setArticleSummary(String articleSummary) {
        this.articleSummary = articleSummary == null ? null : articleSummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.article_title
     *
     * @return the value of t_article.article_title
     *
     * @mbggenerated
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.article_title
     *
     * @param articleTitle the value for t_article.article_title
     *
     * @mbggenerated
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle == null ? null : articleTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.article_file_url
     *
     * @return the value of t_article.article_file_url
     *
     * @mbggenerated
     */
    public String getArticleFileUrl() {
        return articleFileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.article_file_url
     *
     * @param articleFileUrl the value for t_article.article_file_url
     *
     * @mbggenerated
     */
    public void setArticleFileUrl(String articleFileUrl) {
        this.articleFileUrl = articleFileUrl == null ? null : articleFileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.public_datetime
     *
     * @return the value of t_article.public_datetime
     *
     * @mbggenerated
     */
    public Date getPublicDatetime() {
        return publicDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.public_datetime
     *
     * @param publicDatetime the value for t_article.public_datetime
     *
     * @mbggenerated
     */
    public void setPublicDatetime(Date publicDatetime) {
        this.publicDatetime = publicDatetime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.update_datetime
     *
     * @return the value of t_article.update_datetime
     *
     * @mbggenerated
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.update_datetime
     *
     * @param updateDatetime the value for t_article.update_datetime
     *
     * @mbggenerated
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.article_status
     *
     * @return the value of t_article.article_status
     *
     * @mbggenerated
     */
    public Boolean getArticleStatus() {
        return articleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.article_status
     *
     * @param articleStatus the value for t_article.article_status
     *
     * @mbggenerated
     */
    public void setArticleStatus(Boolean articleStatus) {
        this.articleStatus = articleStatus;
    }
}