package me.sonico.bean;

import java.util.Date;

public class TArticleType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_type.article_type_id
     *
     * @mbggenerated
     */
    private Long articleTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_type.article_type_name
     *
     * @mbggenerated
     */
    private String articleTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_type.article_no
     *
     * @mbggenerated
     */
    private String articleNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_type.article_type_serial_no
     *
     * @mbggenerated
     */
    private Integer articleTypeSerialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_type.article_ype_description
     *
     * @mbggenerated
     */
    private String articleYpeDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_type.create_datetime
     *
     * @mbggenerated
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_type.update_datetime
     *
     * @mbggenerated
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_type.article_type_status
     *
     * @mbggenerated
     */
    private Boolean articleTypeStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_type.article_type_id
     *
     * @return the value of t_article_type.article_type_id
     *
     * @mbggenerated
     */
    public Long getArticleTypeId() {
        return articleTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_type.article_type_id
     *
     * @param articleTypeId the value for t_article_type.article_type_id
     *
     * @mbggenerated
     */
    public void setArticleTypeId(Long articleTypeId) {
        this.articleTypeId = articleTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_type.article_type_name
     *
     * @return the value of t_article_type.article_type_name
     *
     * @mbggenerated
     */
    public String getArticleTypeName() {
        return articleTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_type.article_type_name
     *
     * @param articleTypeName the value for t_article_type.article_type_name
     *
     * @mbggenerated
     */
    public void setArticleTypeName(String articleTypeName) {
        this.articleTypeName = articleTypeName == null ? null : articleTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_type.article_no
     *
     * @return the value of t_article_type.article_no
     *
     * @mbggenerated
     */
    public String getArticleNo() {
        return articleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_type.article_no
     *
     * @param articleNo the value for t_article_type.article_no
     *
     * @mbggenerated
     */
    public void setArticleNo(String articleNo) {
        this.articleNo = articleNo == null ? null : articleNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_type.article_type_serial_no
     *
     * @return the value of t_article_type.article_type_serial_no
     *
     * @mbggenerated
     */
    public Integer getArticleTypeSerialNo() {
        return articleTypeSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_type.article_type_serial_no
     *
     * @param articleTypeSerialNo the value for t_article_type.article_type_serial_no
     *
     * @mbggenerated
     */
    public void setArticleTypeSerialNo(Integer articleTypeSerialNo) {
        this.articleTypeSerialNo = articleTypeSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_type.article_ype_description
     *
     * @return the value of t_article_type.article_ype_description
     *
     * @mbggenerated
     */
    public String getArticleYpeDescription() {
        return articleYpeDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_type.article_ype_description
     *
     * @param articleYpeDescription the value for t_article_type.article_ype_description
     *
     * @mbggenerated
     */
    public void setArticleYpeDescription(String articleYpeDescription) {
        this.articleYpeDescription = articleYpeDescription == null ? null : articleYpeDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_type.create_datetime
     *
     * @return the value of t_article_type.create_datetime
     *
     * @mbggenerated
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_type.create_datetime
     *
     * @param createDatetime the value for t_article_type.create_datetime
     *
     * @mbggenerated
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_type.update_datetime
     *
     * @return the value of t_article_type.update_datetime
     *
     * @mbggenerated
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_type.update_datetime
     *
     * @param updateDatetime the value for t_article_type.update_datetime
     *
     * @mbggenerated
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_type.article_type_status
     *
     * @return the value of t_article_type.article_type_status
     *
     * @mbggenerated
     */
    public Boolean getArticleTypeStatus() {
        return articleTypeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_type.article_type_status
     *
     * @param articleTypeStatus the value for t_article_type.article_type_status
     *
     * @mbggenerated
     */
    public void setArticleTypeStatus(Boolean articleTypeStatus) {
        this.articleTypeStatus = articleTypeStatus;
    }
}